name: PlayerChatColor
description: PlayerChatColor
main: com.connorlinfoot.playerchatcolor.Main
version: 1.1
commands:
  chatcolor:
    description: Change your Chat Color
permissions:
  chatcolor.use:
    default: false
  chatcolor.other:
    default: false